name: Test

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules  # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install Dependencies # node module install
        run: yarn

      - name: Test # project build
        run: yarn test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
